services:
  db_blacklist:
    volumes:
      - ./db_data/pgdata:/var/lib/postgresql/data
    container_name: db_blacklist
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 3s
      timeout: 2s
      retries: 5
  blacklist:
    build: .
    depends_on:
      db_blacklist:
        condition: service_healthy
    ports:
      - "8000:8000"
      - "5679:5679" # Debug port
    volumes:
      - .:/app
    environment:
      FLASK_DEBUG: 1
      RDS_USERNAME: postgres
      RDS_PASSWORD: postgres
      RDS_HOSTNAME: db_blacklist
      RDS_PORT: 5432
      RDS_DB_NAME: postgres
      NEW_RELIC_LICENSE_KEY: e99c6967721712d9be312729d85408feFFFFNRAL
      NEW_RELIC_APP_NAME: Blacklist API
      NEW_RELIC_MONITOR_MODE: true
      NEW_RELIC_LOG_LEVEL: info
    command:
      - sh
      - -c
      - |
        pip install debugpy
        newrelic-admin run-program flask --app application run --host=0.0.0.0 -p 8000 --reload

